#!/usr/bin/env bash
set -euo pipefail

# Publishes the packaged Omarchy plugin tree to the distribution repository.
# `omarchy plugin add` clones the default branch full-depth and
# `omarchy plugin update` fast-forwards it, so that branch must always hold a
# complete, self-consistent plugin: QML, manifest, and matching binaries.

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
version="${1:-}"
archive="${2:-}"

plugin_remote="${HARK_PLUGIN_REPO:-https://github.com/konradk/hark-plugin.git}"
plugin_branch="${HARK_PLUGIN_BRANCH:-main}"
release_arch="${HARK_RELEASE_ARCH:-$(go env GOARCH)}"
commit_name="${HARK_PLUGIN_COMMIT_NAME:-github-actions[bot]}"
commit_email="${HARK_PLUGIN_COMMIT_EMAIL:-41898282+github-actions[bot]@users.noreply.github.com}"

if [[ ! "${version}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]; then
  echo "usage: scripts/publish-plugin-repo.sh vMAJOR.MINOR.PATCH [PLUGIN_ARCHIVE]" >&2
  exit 2
fi

archive_root="hark-plugin-${version}-linux-${release_arch}"
if [[ -z "${archive}" ]]; then
  archive="${repo_root}/dist/${archive_root}.tar.gz"
fi
if [[ ! -f "${archive}" ]]; then
  echo "Plugin archive not found: ${archive}" >&2
  echo "Run scripts/release.sh ${version} first." >&2
  exit 1
fi

work_dir="$(mktemp -d)"
cleanup() {
  rm -rf -- "${work_dir}"
}
trap cleanup EXIT

tar -xzf "${archive}" -C "${work_dir}"
staged="${work_dir}/${archive_root}"
[[ -d "${staged}" ]] || {
  echo "Archive did not contain ${archive_root}/." >&2
  exit 1
}

# omarchy-plugin-validate never inspects bin/, so a tree published without the
# runtime installs cleanly and only fails once the shell tries to start it.
for binary in harkd harkctl; do
  [[ -x "${staged}/bin/${binary}" ]] || {
    echo "Packaged plugin is missing an executable bin/${binary}." >&2
    exit 1
  }
done
manifest_version="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["version"])' "${staged}/manifest.json")"
[[ "${manifest_version}" == "${version#v}" ]] || {
  echo "Packaged manifest version ${manifest_version} does not match ${version}." >&2
  exit 1
}

if [[ -z "${PLUGIN_REPO_TOKEN:-}" ]]; then
  echo "PLUGIN_REPO_TOKEN is required to push to ${plugin_remote}." >&2
  exit 1
fi

# Keep the token out of argv and out of the checkout's .git/config.
askpass="${work_dir}/askpass.sh"
# Single quotes are required: the token must expand when git runs this helper,
# not while the helper is being written.
# shellcheck disable=SC2016
printf '#!/usr/bin/env bash\nprintf %%s "${PLUGIN_REPO_TOKEN}"\n' >"${askpass}"
chmod 0700 "${askpass}"
export GIT_ASKPASS="${askpass}"
export GIT_TERMINAL_PROMPT=0
export PLUGIN_REPO_TOKEN

authenticated_remote="${plugin_remote/https:\/\//https://x-access-token@}"
checkout="${work_dir}/plugin-repo"
git clone --quiet "${authenticated_remote}" "${checkout}"

# Never infer the branch from the clone's HEAD: a repository whose remote HEAD
# is unset or stale checks out nothing, and committing from there would build a
# root commit that can no longer fast-forward the published branch.
remote_branches=()
while IFS= read -r remote_branch; do
  # refs/remotes/origin/HEAD shortens to a bare "origin", not "origin/HEAD".
  [[ -n "${remote_branch}" && "${remote_branch}" != "origin" ]] && remote_branches+=("${remote_branch}")
done < <(git -C "${checkout}" for-each-ref --format='%(refname:short)' refs/remotes/origin)

if git -C "${checkout}" rev-parse --verify --quiet "refs/remotes/origin/${plugin_branch}" >/dev/null; then
  git -C "${checkout}" checkout --quiet -B "${plugin_branch}" "refs/remotes/origin/${plugin_branch}"
elif (( ${#remote_branches[@]} == 0 )); then
  git -C "${checkout}" symbolic-ref HEAD "refs/heads/${plugin_branch}"
else
  echo "${plugin_remote} has no '${plugin_branch}' branch but does have: ${remote_branches[*]}" >&2
  echo "Publishing a second branch would leave omarchy cloning the wrong one." >&2
  exit 1
fi

# Replace the worktree wholesale so files dropped from the package disappear.
find "${checkout}" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf -- {} +
cp -a "${staged}/." "${checkout}/"

source_commit="$(git -C "${repo_root}" rev-parse HEAD)"
cat >"${checkout}/README.md" <<NOTICE
<!--
Generated by scripts/publish-plugin-repo.sh. Do not edit this repository by
hand; changes belong in https://github.com/konradk/hark and are republished on
the next release.
-->

# Hark (Omarchy plugin)

Packaged Omarchy plugin build of [Hark](https://github.com/konradk/hark),
released as ${version} from commit \`${source_commit}\`.

\`\`\`bash
omarchy plugin add ${plugin_remote} --enable
omarchy-shell shell summon hark
\`\`\`

Update with \`omarchy plugin update hark\`.

Source, documentation, issues, and security reporting all live in the
[main repository](https://github.com/konradk/hark).

## License

[MIT](LICENSE).
NOTICE

git -C "${checkout}" add -A
if git -C "${checkout}" diff --cached --quiet; then
  echo "Plugin repository already matches ${version}; nothing to commit."
else
  git -C "${checkout}" \
    -c "user.name=${commit_name}" \
    -c "user.email=${commit_email}" \
    commit --quiet -m "Hark ${version}" -m "Built from konradk/hark@${source_commit}."
fi

git -C "${checkout}" tag -f "${version}"
git -C "${checkout}" push --quiet origin "HEAD:refs/heads/${plugin_branch}"
git -C "${checkout}" push --quiet --force origin "refs/tags/${version}"

printf 'Published Hark %s to %s (%s)\n' "${version}" "${plugin_remote}" "${plugin_branch}"
